version: 0.1
phases:
  install:
    commands:
      - sudo pip install --upgrade awscli
      - aws --version
      - sudo pip install 'chalice>=1.6.0,<1.7.0'
      - sudo pip install -r requirements.txt
      - sudo pip install pytest
  build:
    commands:
      - pytest -v
  post_build:
    commands:
      - chalice package /tmp/packaged
      - aws cloudformation package --template-file /tmp/packaged/sam.json --s3-bucket ${APP_S3_BUCKET} --output-template-file transformed.yaml
artifacts:
  type: zip
  files:
    - transformed.yaml
